apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: recommendation
data:
  APP_ENV: "production"
  API_PORT: "8000"
  LOG_LEVEL: "INFO"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  MODEL_NAME: "recommendation-engine"
  MODEL_STAGE: "Production"
